server:
  port: 8081
  servlet:
    context-path: '/auth-service/'

spring:
  output:
    ansi:
      enabled: Always
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddlAuto: update
      jdbc:
        lob.nonContextualCreation: true
    properties:
      hibernate:
        formatSql: true
        showSql: true
